apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  type: NodePort  # Change this
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30306  # Pick a port in range 30000-32767
  selector:
    app.kubernetes.io/name: mariadb

