name: Build and Deploy Backend

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
          
      - name: Build Spring Boot Application
        run: |
          chmod +x gradlew
          ./gradlew build -x test
          
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/noticeboard_backend:${{ github.sha }} .
          
      # Scan and upload results to Security tab
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/noticeboard_backend:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          
      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
          
      # Check for critical vulnerabilities only
      - name: Check for critical vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/noticeboard_backend:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'
          ignore-unfixed: true
          
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/noticeboard_backend:${{ github.sha }}
          
      - name: Update Helm chart values
        run: |
          sed -i "s|tag:.*|tag: ${{ github.sha }}|g" helm/values.yaml
          
      - name: Commit updated values
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update image tag in Helm chart [skip ci]
          file_pattern: helm/values.yaml
