name: Build and Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Build Spring Boot Application
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}

      - name: Update Helm chart values
        run: |
          sed -i "s|tag:.*|tag: ${{ github.sha }}|g" helm/values.yaml

      - name: Commit updated values
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update image tag in Helm chart
          file_pattern: helm/values.yaml
